# Use vi-style keys in copy mode
setw -g mode-keys vi
# Use vi-style keybindings for pane resizing, copy mode, etc.
set -g status-keys vi
set -g mouse on     # Enable mouse support
set -g history-limit 10000  # Longer scrollback

